volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
networks:
  default:
    name: local-development-network
services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@development.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "15432:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - default
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: [ 'start', ]
    volumes:
      - ./keycloak.pfx:/app/certs/keycloak.pfx
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_HTTP_ENABLED: true
      KC_HTTPS_KEY_STORE_FILE: /app/certs/keycloak.pfx
      KC_HTTPS_KEY_STORE_PASSWORD: password
      KC_FEATURES: token-exchange
    ports:
      - "9000:8080"
      - "9443:8443"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
