### GET request to Keycloak server to obtain OpenID configuration
GET {{oauthUrl}}/realms/{{realm}}/.well-known/openid-configuration
Content-Type: application/json

### POST request to Keycloak server to obtain an access token
POST {{oauthUrl}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type = password &
client_id = {{clientId}} &
username = {{clientUsername}} &
password = {{clientSecret}}
> {%
    client.global.set("access_token", response.body.access_token)
%}

###
GET {{resourceServerUrl}}/api/users
Content-Type: application/json
Authorization: Bearer {{access_token}}

###
GET {{resourceServerUrl}}/api/users/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

###
GET {{resourceServerUrl}}/api/keycloak/clients
Content-Type: application/json
Authorization: Bearer {{access_token}}

###
GET {{resourceServerUrl}}/api/keycloak/clients/<<valid_id_From_previous_response>>
Content-Type: application/json
Authorization: Bearer {{access_token}}

###
GET {{resourceServerUrl}}/api/keycloak/roles
Content-Type: application/json
Authorization: Bearer {{access_token}}

###
GET {{resourceServerUrl}}/api/keycloak/roles/default-roles-{{realm}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

###
GET {{resourceServerUrl}}/api/keycloak/users
Content-Type: application/json
Authorization: Bearer {{access_token}}

###
GET {{resourceServerUrl}}/api/keycloak/users/<<valid_id_From_previous_response>>
Content-Type: application/json
Authorization: Bearer {{access_token}}

###
